### ISSUE TITLE
Error when installing with Obtanium: "Some Errors Occurred: Invalid [ltd.ucode.slide]"

### ISSUE THREAD

**Issue by EoN-kCw1u5Sh1Ws** [bqv/slide#1]
Slide version: 0.0.1
Android version: 13

When trying to install using Obtanium.

Ltd.ucode.slide is listed as 2023-06-30 22:24:47.000Z

App not installed as packaged invalid when trying to install using File Manager.

**Comment by bqv** [comment]
I wonder, do you have Slide for Reddit installed too?

**Comment by bqv** [comment]
Let me know or reopen if the secondattempt apk (or any later version) still doesn't work for you, someone on lemmy has said that it works for them, so I'm assuming this has fixed the issue

**Comment by EoN-kCw1u5Sh1Ws** [comment]
Yes, the second attempt apk has installed fine. Thank you. I didn't have Slide for Reddit installed.
