### ISSUE TITLE
App still tries to open Reddit links, cannot open Lemmy links.

### ISSUE THREAD

**Issue by curbia** [bqv/slide#29]
Slide version: 0.0.2
Android version: 11

![image](https://github.com/bqv/slide/assets/87792521/76c6e0c2-7a5d-483c-b1d4-5ae9fd87008f)

I understand that due to the number of domains the are associated with Lemmy, and the fact that the list will continue to grow forever, it may not be possible to easily associate a large number of Lemmy links with Slide. However, we should probably remove the associations to Reddit links and perhaps associate a few of the largest instances.

**Comment by bqv** [comment]
Good point. I'll at least remove the reddit ones to not be a pain
