### ISSUE TITLE
Post title is not fully visible

### ISSUE THREAD

**Issue by varaki** [bqv/slide#6]
Slide version: 0.0.2-alpha
Android version: 12

Posts are not fully visible, when I open them, they appear cropped, overlapped by the app header:
![Screenshot_20230701-110250_crDroid Home](https://github.com/bqv/slide/assets/23281360/484ee6f4-0eb1-446f-a9be-2fdbb1cad767)

**Comment by bqv** [comment]
Not entirely sure whats happening here if I'm honest. Did you have this issue with Reddit Slide too, or is this new?

At a guess, updating targetapi has broken compatibility with something, but that would be bizarre for A12

Your FAB is also in the navbar, is this a custom rom?

**Comment by varaki** [comment]
> Not entirely sure whats happening here if I'm honest. Did you have this issue with Reddit Slide too, or is this new?
> 
> At a guess, updating targetapi has broken compatibility with something, but that would be bizarre for A12
> 
> Your FAB is also in the navbar, is this a custom rom?

Yes, I forgot to mention, it's CrDroid 8.12, with gesture navigation enabled, so not with the usual 2 or 3 button navigation.
I have not used the original slide on android 12, the reason being it was already abandoned and there was an issue with opening reddit links in the app. I even rebuilt a modified version of that to solve the issue, but eventually moved on to the actively developed Infinity back then.
